version: "3.8"
services:
  zerowasteengine:
    container_name: zerowasteengine
    build:
      context: ./ZeroWasteEngine
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    